remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Haruka Takagi's Data Science Portfolio
logo: images/simon.png
description: Thanks for stopping by my data science portfolio! Simon welcomes you to this page! Grab a coffee and please browse around the projects that are of interest to you! :D
show_downloads: true
google_analytics: true
theme: jekyll-theme-minimal
