remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Haruka Takagi's Data Science Portfolio
logo: images/cute_simon.png
description: Thanks for stopping by my data science portfolio! Simon welcomes you to this page! Grab a coffee and please browse around the projects that are of interest to you! :D  <br /> <br /> Feel free to contact me via email! <br /> haruka.takagi.datascience@gmail.com  
<object data="Haruka_Takagi_CV_Aug_7_2022_PDF.pdf" width="1000" height="1000" type='application/pdf'/>
show_downloads: false
google_analytics: true
theme: jekyll-theme-minimal
