remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Haruka Takagi's Data Science Portfolio
logo: images/cute_simon.png
description: Thanks for stopping by my data science portfolio! Simon welcomes you to this page! Grab a coffee and please browse around the projects that are of interest to you! :D  <br /> <br /> I am an aspiring data scientist! I have experience working as a Machine Learning Engineer and have been on multiple academic finance research projects as a researcher and Co-Author. I am currently look for full-time oppurtunities for May 2023 in Toronto, Ontario, Canada as a data scientist, data analyst or financial analyst! <br /> <br /> Please check out my linkedin page for my resume! <br /> https://www.linkedin.com/in/haruka-takagi/ <br /> <br /> Here is my email! <br /> haruka.takagi.datascience@gmail.com
show_downloads: false
google_analytics: true
theme: jekyll-theme-minimal
